### 예외 처리기 (exception handler)
> CLR은 예외 처리기가 있다면 해당 에외 처리기로 넘기고,<br>
> 없다면 예외 메시지를 출력하고 프로그램을 종료한다.
<br>

▼ try/catch 예약어
````csharp
int divisor = 0;

try
{
    // System.DivideByZeroException
    int quotient = 10 / divisor;
}
catch
{
    try
    {
        // 사용자 코드
    }
    catch  { }
}
````
- 프로그램이 종료되지 않고 실행 흐름이 catch 블록으로 넘어간다.
- try/catch 중첩이 가능하다.
<br>

▼ finally 예약어
````csharp
try
{
    int quotient = 10 / divisor;
    Console.WriteLine("예외가 발생하지 않으면 실행됨!");
}
catch
{
    Console.WriteLine("예외가 발생하면 실행됨!");
}
finally
{
    Console.WriteLine("언제나 실행됨!");
}
````
- 예외가 발생하는 것과 상관없이 언제나 실행된다.
- finally 블록은 자원을 해제하는 코드를 넣어두는 용도로 적합하다. (FileStream)
<br>


